[versions]
# Keeping the project in good shape and having all the dependencies up-to-date requires time and effort,
# but it is possible to automate that process using Dependabot.
# Dependabot is a bot provided by GitHub to check the build configuration files and review any outdated
# or insecure dependencies of yours – in case if any update is available,
# it creates a new pull request providing the proper change.

# libraries
junit = "4.13.2"

# plugins
changelog = "2.2.1"
intelliJPlatform = "2.2.1"
kotlin = "2.1.10"
kover = "0.8.3"
qodana = "2024.2.3"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }

[plugins]
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
intelliJPlatform = { id = "org.jetbrains.intellij.platform", version.ref = "intelliJPlatform" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
qodana = { id = "org.jetbrains.qodana", version.ref = "qodana" }
